// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http)
package capture

import (
	"database/sql"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/walterwanderley/am2manager"
	"github.com/walterwanderley/am2manager/cmd/am2server/internal/server"
)

type Service struct {
	querier *Queries
}

func NewService(querier *Queries) *Service {
	return &Service{querier: querier}
}

func (s *Service) handleAddCapture() http.HandlerFunc {
	type request struct {
		UserID      *int64  `form:"user_id" json:"user_id"`
		Name        string  `form:"name" json:"name"`
		Description *string `form:"description" json:"description"`
		Data        []byte  `form:"data" json:"data"`
	}
	type response struct {
		LastInsertId int64 `json:"last_insert_id"`
		RowsAffected int64 `json:"rows_affected"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		req, err := server.Decode[request](r)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		var arg addCaptureParams
		if req.UserID != nil {
			arg.UserID = sql.NullInt64{Valid: true, Int64: *req.UserID}
		}
		arg.Name = req.Name
		if req.Description != nil {
			arg.Description = sql.NullString{Valid: true, String: *req.Description}
		}

		file, handler, err := r.FormFile("data")
		if err != nil {
			slog.Error("upload file", "error", err)
			http.Error(w, "upload file error", http.StatusInternalServerError)
			return
		}
		defer file.Close()
		if arg.Name == "" {
			arg.Name = handler.Filename
		}

		data, err := io.ReadAll(file)
		if err != nil {
			slog.Error("read file", "error", err)
			http.Error(w, "read file error", http.StatusInternalServerError)
			return
		}

		var am2data am2manager.Am2Data
		if err := am2data.UnmarshalBinary(data); err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}

		arg.Data, err = am2data.MarshalBinary()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}

		arg.Am2Hash = am2data.HashAm2()
		arg.DataHash = am2data.HashData()

		result, err := s.querier.addCapture(r.Context(), arg)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "AddCapture")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		lastInsertId, _ := result.LastInsertId()
		rowsAffected, _ := result.RowsAffected()
		server.Encode(w, r, http.StatusOK, response{
			LastInsertId: lastInsertId,
			RowsAffected: rowsAffected,
		})
	}
}

func (s *Service) handleGetCapture() http.HandlerFunc {
	type request struct {
		Id int64 `form:"id" json:"id"`
	}
	type response struct {
		ID          int64      `json:"id,omitempty"`
		UserID      *int64     `json:"user_id,omitempty"`
		Name        string     `json:"name,omitempty"`
		Description *string    `json:"description,omitempty"`
		Am2Hash     string     `json:"am2_hash,omitempty"`
		DataHash    string     `json:"data_hash,omitempty"`
		Data        []byte     `json:"data,omitempty"`
		Downloads   int64      `json:"downloads,omitempty"`
		CreatedAt   time.Time  `json:"created_at,omitempty"`
		UpdatedAt   *time.Time `json:"updated_at,omitempty"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.Id = v
			}
		}
		id := req.Id

		result, err := s.querier.GetCapture(r.Context(), id)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "GetCapture")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		var res response
		res.ID = result.ID
		if result.UserID.Valid {
			res.UserID = &result.UserID.Int64
		}
		res.Name = result.Name
		if result.Description.Valid {
			res.Description = &result.Description.String
		}
		res.Am2Hash = result.Am2Hash
		res.DataHash = result.DataHash
		res.Data = result.Data
		res.Downloads = result.Downloads
		res.CreatedAt = result.CreatedAt
		if result.UpdatedAt.Valid {
			res.UpdatedAt = &result.UpdatedAt.Time
		}
		server.Encode(w, r, http.StatusOK, res)
	}
}

func (s *Service) handleGetCaptureFile() http.HandlerFunc {
	type request struct {
		Id int64 `form:"id" json:"id"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.Id = v
			}
		}
		id := req.Id

		result, err := s.querier.GetCaptureFile(r.Context(), id)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "GetCaptureFile")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		filename := strings.TrimSuffix(result.Name, ".am2data")
		filename = strings.TrimSuffix(strings.TrimSuffix(filename, ".am2Data"), ".am2")

		filename += ".am2data"

		w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
		w.Header().Set("Content-Length", fmt.Sprint(len(result.Data)))
		w.Header().Set("Content-Type", "application/octet-stream")
		w.Write(result.Data)
	}
}

func (s *Service) handleListCaptures() http.HandlerFunc {
	type response struct {
		ID          int64     `json:"id,omitempty"`
		Name        string    `json:"name,omitempty"`
		Description *string   `json:"description,omitempty"`
		Downloads   int64     `json:"downloads,omitempty"`
		CreatedAt   time.Time `json:"created_at,omitempty"`
	}

	return func(w http.ResponseWriter, r *http.Request) {

		result, err := s.querier.ListCaptures(r.Context())
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "ListCaptures")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		res := make([]response, 0)
		for _, r := range result {
			var item response
			item.ID = r.ID
			item.Name = r.Name
			if r.Description.Valid {
				item.Description = &r.Description.String
			}
			item.Downloads = r.Downloads
			item.CreatedAt = r.CreatedAt
			res = append(res, item)
		}
		server.Encode(w, r, http.StatusOK, res)
	}
}

func (s *Service) handleRemoveCapture() http.HandlerFunc {
	type request struct {
		Id int64 `form:"id" json:"id"`
	}
	type response struct {
		LastInsertId int64 `json:"last_insert_id"`
		RowsAffected int64 `json:"rows_affected"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.Id = v
			}
		}
		id := req.Id

		result, err := s.querier.RemoveCapture(r.Context(), id)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "RemoveCapture")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		lastInsertId, _ := result.LastInsertId()
		rowsAffected, _ := result.RowsAffected()
		server.Encode(w, r, http.StatusOK, response{
			LastInsertId: lastInsertId,
			RowsAffected: rowsAffected,
		})
	}
}
