# fly.toml app configuration file generated for am2manager on 2024-07-29T21:54:53-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'am2manager'
primary_region = 'gru'

[build]

[mounts]
  source = "am2_data"
  destination = "/data"

[env]
  PORT = '8080'
  AWS_ACCESS_KEY_ID = 'tid_vfQUpnnBvMZAwCjSUU_HvIpyvCTJXO_DkysPFWzamRLSmMWjCb'
  AWS_ENDPOINT_URL_S3 = 'https://fly.storage.tigris.dev'
  AWS_REGION = 'auto'  
  BUCKET_NAME = 'weathered-sun-91'
  LITESTREAM_URL = 's3:/am2manager'
  LITESTREAM_FORCE_PATH_STYLE = 'true'
  DSN = '/data/as2manager.db'
  REDIRECT_SERVER = 'https://am2manager.fly.dev'
  GOMEMLIMIT = '200MiB' 
  ADMIN = 'walterwanderley@gmail.com'


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/liveness"
    port = 8080
    timeout = "10s"
    type = "http"