// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http). DO NOT EDIT.

package review

import (
	"database/sql"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/walterwanderley/am2manager/cmd/am2server/internal/server"
)

type Service struct {
	querier *Queries
}

func NewService(querier *Queries) *Service {
	return &Service{querier: querier}
}

func (s *Service) handleAddReview() http.HandlerFunc {
	type request struct {
		UserID    *int64  `form:"user_id" json:"user_id"`
		CaptureID int64   `form:"capture_id" json:"capture_id"`
		Rate      int64   `form:"rate" json:"rate"`
		Comment   *string `form:"comment" json:"comment"`
	}
	type response struct {
		LastInsertId int64 `json:"last_insert_id"`
		RowsAffected int64 `json:"rows_affected"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		req, err := server.Decode[request](r)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		var arg AddReviewParams
		if req.UserID != nil {
			arg.UserID = sql.NullInt64{Valid: true, Int64: *req.UserID}
		}
		arg.CaptureID = req.CaptureID
		arg.Rate = req.Rate
		if req.Comment != nil {
			arg.Comment = sql.NullString{Valid: true, String: *req.Comment}
		}

		result, err := s.querier.AddReview(r.Context(), arg)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "AddReview")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		lastInsertId, _ := result.LastInsertId()
		rowsAffected, _ := result.RowsAffected()
		server.Encode(w, r, http.StatusOK, response{
			LastInsertId: lastInsertId,
			RowsAffected: rowsAffected,
		})
	}
}

func (s *Service) handleListReviewsByCapture() http.HandlerFunc {
	type request struct {
		CaptureID int64 `form:"capture_id" json:"capture_id"`
	}
	type response struct {
		ID        int64      `json:"id,omitempty"`
		UserID    *int64     `json:"user_id,omitempty"`
		CaptureID int64      `json:"capture_id,omitempty"`
		Rate      int64      `json:"rate,omitempty"`
		Comment   *string    `json:"comment,omitempty"`
		CreatedAt time.Time  `json:"created_at,omitempty"`
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("capture_id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.CaptureID = v
			}
		}
		captureID := req.CaptureID

		result, err := s.querier.ListReviewsByCapture(r.Context(), captureID)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "ListReviewsByCapture")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		res := make([]response, 0)
		for _, r := range result {
			var item response
			item.ID = r.ID
			if r.UserID.Valid {
				item.UserID = &r.UserID.Int64
			}
			item.CaptureID = r.CaptureID
			item.Rate = r.Rate
			if r.Comment.Valid {
				item.Comment = &r.Comment.String
			}
			item.CreatedAt = r.CreatedAt
			if r.UpdatedAt.Valid {
				item.UpdatedAt = &r.UpdatedAt.Time
			}
			res = append(res, item)
		}
		server.Encode(w, r, http.StatusOK, res)
	}
}

func (s *Service) handleListReviewsByUser() http.HandlerFunc {
	type request struct {
		UserID *int64 `form:"user_id" json:"user_id"`
	}
	type response struct {
		ID        int64      `json:"id,omitempty"`
		UserID    *int64     `json:"user_id,omitempty"`
		CaptureID int64      `json:"capture_id,omitempty"`
		Rate      int64      `json:"rate,omitempty"`
		Comment   *string    `json:"comment,omitempty"`
		CreatedAt time.Time  `json:"created_at,omitempty"`
		UpdatedAt *time.Time `json:"updated_at,omitempty"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("user_id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.UserID = &v
			}
		}
		var userID sql.NullInt64
		if req.UserID != nil {
			userID = sql.NullInt64{Valid: true, Int64: *req.UserID}
		}

		result, err := s.querier.ListReviewsByUser(r.Context(), userID)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "ListReviewsByUser")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		res := make([]response, 0)
		for _, r := range result {
			var item response
			item.ID = r.ID
			if r.UserID.Valid {
				item.UserID = &r.UserID.Int64
			}
			item.CaptureID = r.CaptureID
			item.Rate = r.Rate
			if r.Comment.Valid {
				item.Comment = &r.Comment.String
			}
			item.CreatedAt = r.CreatedAt
			if r.UpdatedAt.Valid {
				item.UpdatedAt = &r.UpdatedAt.Time
			}
			res = append(res, item)
		}
		server.Encode(w, r, http.StatusOK, res)
	}
}

func (s *Service) handleRemoveReview() http.HandlerFunc {
	type request struct {
		Id int64 `form:"id" json:"id"`
	}
	type response struct {
		LastInsertId int64 `json:"last_insert_id"`
		RowsAffected int64 `json:"rows_affected"`
	}

	return func(w http.ResponseWriter, r *http.Request) {
		var req request
		if str := r.PathValue("id"); str != "" {
			if v, err := strconv.ParseInt(str, 10, 64); err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			} else {
				req.Id = v
			}
		}
		id := req.Id

		result, err := s.querier.RemoveReview(r.Context(), id)
		if err != nil {
			slog.Error("sql call failed", "error", err, "method", "RemoveReview")
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		lastInsertId, _ := result.LastInsertId()
		rowsAffected, _ := result.RowsAffected()
		server.Encode(w, r, http.StatusOK, response{
			LastInsertId: lastInsertId,
			RowsAffected: rowsAffected,
		})
	}
}
