openapi: 3.0.3
info:
  contact:
      name: sqlc-http
      url: https://github.com/walterwanderley/sqlc-http
  description: Manage and share am2/am2data (SincoANN profile) files
  title: am2 Server
  version: 0.0.1
  
  
tags:
  - capture
  - review
  - user
  
  
paths:
  /captures/{capture_id}/reviews:
      get:
          parameters:
              - in: path
                name: capture_id
                schema:
                  format: int64
                  type: integer
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              items:
                                  $ref: '#/components/schemas/reviewReview'
                              type: array
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: ListReviewsByCapture
          tags:
              - review
  /captures/{id}:
      patch:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          requestBody:
              content:
                  application/json:
                      schema:
                          properties:
                              demo_link:
                                  type: string
                              description:
                                  type: string
                              has_cab:
                                  type: boolean
                              name:
                                  type: string
                              type:
                                  type: string
                          type: object
                  application/x-www-form-urlencoded:
                      schema:
                          properties:
                              demo_link:
                                  type: string
                              description:
                                  type: string
                              has_cab:
                                  type: boolean
                              name:
                                  type: string
                              type:
                                  type: string
                          type: object
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: UpdateCapture
          tags:
              - capture
  /captures/{id}/file:
      get:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          responses:
              "200":
                  content:
                      application/octet-stream:
                          schema:
                              format: binary
                              type: string
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: GetCaptureFile
          tags:
              - capture
  /reviews:
      post:
          requestBody:
              content:
                  application/json:
                      schema:
                          properties:
                              capture_id:
                                  format: int64
                                  type: integer
                              comment:
                                  type: string
                              rate:
                                  format: int64
                                  type: integer
                              user_id:
                                  format: int64
                                  type: integer
                          type: object
                  application/x-www-form-urlencoded:
                      schema:
                          properties:
                              capture_id:
                                  format: int64
                                  type: integer
                              comment:
                                  type: string
                              rate:
                                  format: int64
                                  type: integer
                              user_id:
                                  format: int64
                                  type: integer
                          type: object
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: AddReview
          tags:
              - review
  /reviews/{id}:
      delete:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: RemoveReview
          tags:
              - review
  /users/{id}:
      get:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              $ref: '#/components/schemas/userUser'
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: GetUser
          tags:
              - user
  /users/{id}/name:
      patch:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          requestBody:
              content:
                  application/json:
                      schema:
                          properties:
                              name:
                                  type: string
                          type: object
                  application/x-www-form-urlencoded:
                      schema:
                          properties:
                              name:
                                  type: string
                          type: object
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: UpdateUserName
          tags:
              - user
  
  /captures:
    get:
      post:
          requestBody:
              content:
                  multipart/form-data:
                      schema:
                          properties:
                              data:
                                  format: binary
                                  type: string
                              demo_link:
                                  type: string
                              description:
                                  type: string
                              has_cab:
                                  type: boolean
                              name:
                                  type: string
                              type:
                                  type: string
                              user_id:
                                  format: int64
                                  type: integer
                          type: object
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: AddCapture
          tags:
              - capture
      summary: SearchCaptures
      tags:
          - capture
      
      
      parameters:
        - name: arg
          in: query
          schema:
            type: string
        - name: offset
          in: query
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/captureSearchCapturesRow"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/{user_id}/reviews:
    get:
      summary: ListReviewsByUser
      tags:
          - review
      
      
      parameters:
        - name: user_id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/reviewReview"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users:
    get:
      summary: GetUserByEmail
      tags:
          - user
      
      
      parameters:
        - name: email
          in: query
          schema:
            type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userUser"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/count:
    get:
      summary: ContUsers
      tags:
          - user
      
      
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  
components:
  schemas:
    captureCustomCapture:
        properties:
            am2_hash:
                type: string
            created_at:
                format: date-time
                type: string
            data:
                format: binary
                type: string
            data_hash:
                type: string
            description:
                type: string
            downloads:
                format: int64
                type: integer
            has_cab:
                type: boolean
            id:
                format: int64
                type: integer
            name:
                type: string
            type:
                type: string
            updated_at:
                format: date-time
                type: string
            user_id:
                format: int64
                type: integer
        type: object
    captureListCapturesRow:
        properties:
            created_at:
                format: date-time
                type: string
            description:
                type: string
            downloads:
                format: int64
                type: integer
            id:
                format: int64
                type: integer
            name:
                type: string
        type: object
    
    captureSearchCapturesRow:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        downloads:
          type: integer
          format: int64
        has_cab:
          type: boolean
        type:
          type: string
        created_at:
          type: string
          format: date-time
        demo_link:
          type: string
    reviewReview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        capture_id:
          type: integer
          format: int64
        rate:
          type: integer
          format: int64
        comment:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    userUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        name:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        picture:
          type: string
    
  
