openapi: 3.0.3
info:
  contact:
      name: sqlc-http
      url: https://github.com/walterwanderley/sqlc-http
  description: Manage and share am2/am2data (SincoANN profile) files
  title: am2 Server
  version: 0.0.1
  
  
tags:
  - capture
  - review
  - user
  
  
paths:
  /captures-upload:
      post:
          requestBody:
              content:
                  multipart/form-data:
                      schema:
                          properties:
                              data:
                                  format: binary
                                  type: string
                              description:
                                  type: string
                              has_cab:
                                  type: boolean
                              name:
                                  type: string
                              type:
                                  type: string
                              user_id:
                                  format: int64
                                  type: integer
                          type: object
          responses:
              "200":
                  content:
                      application/json:
                          schema:
                              properties:
                                  last_insert_id:
                                      format: int64
                                      type: integer
                                  rows_affected:
                                      format: int64
                                      type: integer
                              type: object
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: AddCapture
          tags:
              - capture
  /captures/{id}/file:
      get:
          parameters:
              - in: path
                name: id
                schema:
                  format: int64
                  type: integer
          responses:
              "200":
                  content:
                      application/octet-stream:
                          schema:
                              format: binary
                              type: string
                  description: OK
              default:
                  content:
                      text/plain:
                          schema:
                              type: string
                  description: Error message
          summary: GetCaptureFile
          tags:
              - capture
  
  /captures:
    get:
      summary: SearchCaptures
      tags:
          - capture
      
      
      parameters:
        - name: arg
          in: query
          schema:
            type: string
        - name: offset
          in: query
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/captureSearchCapturesRow"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /captures/{id}:
    get:
      summary: GetCapture
      tags:
          - capture
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/captureCapture"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    delete:
      summary: RemoveCapture
      tags:
          - capture
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /captures/{capture_id}/reviews:
    get:
      summary: ListReviewsByCapture
      tags:
          - review
      
      
      parameters:
        - name: capture_id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/reviewReview"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /reviews:
    post:
      summary: AddReview
      tags:
          - review
      
      
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
                capture_id:
                  type: integer
                  format: int64
                rate:
                  type: integer
                  format: int64
                comment:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  format: int64
                capture_id:
                  type: integer
                  format: int64
                rate:
                  type: integer
                  format: int64
                comment:
                  type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /reviews/{id}:
    delete:
      summary: RemoveReview
      tags:
          - review
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/{user_id}/reviews:
    get:
      summary: ListReviewsByUser
      tags:
          - review
      
      
      parameters:
        - name: user_id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/reviewReview"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users:
    post:
      summary: AddUser
      tags:
          - user
      
      
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                email:
                  type: string
                pass:
                  type: string
                status:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                login:
                  type: string
                email:
                  type: string
                pass:
                  type: string
                status:
                  type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/count:
    get:
      summary: ContUsers
      tags:
          - user
      
      
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/{id}:
    get:
      summary: GetUser
      tags:
          - user
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userUser"
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    delete:
      summary: RemoveUser
      tags:
          - user
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/{id}/pass:
    patch:
      summary: SetUserPassword
      tags:
          - user
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pass:
                  type: string
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                pass:
                  type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  /users/{id}/token/{pass}:
    get:
      summary: ValidateUserEmail
      tags:
          - user
      
      
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            format: int64
        - name: pass
          in: path
          schema:
            type: string
      
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  last_insert_id:
                    type: integer
                    format: int64
                  rows_affected:
                    type: integer
                    format: int64
          
        "default":    
          description: Error message
          content:
            text/plain:
              schema:
                type: string  
    
  
components:
  schemas:
    captureListCapturesRow:
        properties:
            created_at:
                format: date-time
                type: string
            description:
                type: string
            downloads:
                format: int64
                type: integer
            id:
                format: int64
                type: integer
            name:
                type: string
        type: object
    
    captureCapture:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        type:
          type: string
        has_cab:
          type: boolean
        am2_hash:
          type: string
        data_hash:
          type: string
        data:
          type: string
          format: binary
        downloads:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    captureSearchCapturesRow:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        downloads:
          type: integer
          format: int64
        fav:
          type: integer
          format: int64
        has_cab:
          type: boolean
        type:
          type: string
        created_at:
          type: string
          format: date-time
    reviewReview:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        capture_id:
          type: integer
          format: int64
        rate:
          type: integer
          format: int64
        comment:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    userUser:
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        email:
          type: string
        pass:
          type: string
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
  
