// Code generated by sqlc-http (https://github.com/walterwanderley/sqlc-http). DO NOT EDIT.

package main

import (
	"database/sql"
	"net/http"

	capture_app "github.com/walterwanderley/am2manager/cmd/am2server/internal/capture"
	review_app "github.com/walterwanderley/am2manager/cmd/am2server/internal/review"
	user_app "github.com/walterwanderley/am2manager/cmd/am2server/internal/user"
)

func registerHandlers(mux *http.ServeMux, db *sql.DB) {
	captureService := capture_app.NewService(capture_app.New(db))
	captureService.RegisterHandlers(mux)
	reviewService := review_app.NewService(review_app.New(db))
	reviewService.RegisterHandlers(mux)
	userService := user_app.NewService(user_app.New(db))
	userService.RegisterHandlers(mux)
}
