// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package user

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :execresult
INSERT INTO user(name, email, status, picture) 
VALUES(?,?,?,?)
`

type AddUserParams struct {
	Name    string
	Email   string
	Status  string
	Picture sql.NullString
}

// http: POST /users
func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addUser,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.Picture,
	)
}

const contUsers = `-- name: ContUsers :one
SELECT count(*) FROM user
`

// http: GET /users/count
func (q *Queries) ContUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, contUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, status, created_at, updated_at, picture FROM user WHERE id = ?
`

// http: GET /users/{id}
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Picture,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, status, created_at, updated_at, picture from user WHERE email = ?
`

// http: GET /users
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Picture,
	)
	return i, err
}

const updateUserPicture = `-- name: updateUserPicture :execresult
UPDATE user SET picture = ?, updated_at = now()  WHERE id = ?
`

type updateUserPictureParams struct {
	Picture sql.NullString
	ID      int64
}

func (q *Queries) updateUserPicture(ctx context.Context, arg updateUserPictureParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUserPicture, arg.Picture, arg.ID)
}
